GET http://localhost:1337/api/products/?populate=picture
###
GET http://localhost:1337/api/products/34?populate=picture
###
GET http://127.0.0.1:1337/api/cart-items/?populate=product.picture
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ1NjU0MzA2LCJleHAiOjE2NDgyNDYzMDZ9.ZQEioZyY-N8axr44siZOzoGVfN1JfGNnM9xXdH6-hGw
###
POST http://127.0.0.1:1337/api/cart-items/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ1NjU0MzA2LCJleHAiOjE2NDgyNDYzMDZ9.ZQEioZyY-N8axr44siZOzoGVfN1JfGNnM9xXdH6-hGw
Content-Type: application/json

{"data":{
  "user_id":"3",
  "product":"3",
  "Quantity":"2"
}}
###
//http://localhost:1337/api/posts?filters[product][$eq]=7
###
GET http://127.0.0.1:1337/api/cart-items/?populate=product&filters[user][$eq]=3
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ1MjE0NjAzLCJleHAiOjE2NDc4MDY2MDN9.BENiDZQXzMbiVUVoQ3b5NKV_SalqR0UwMc2p8ri3mxE
###
GET http://127.0.0.1:1337/api/cart-items/34?populate=*
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ1MjE0NjAzLCJleHAiOjE2NDc4MDY2MDN9.BENiDZQXzMbiVUVoQ3b5NKV_SalqR0UwMc2p8ri3mxE
###
DELETE http://127.0.0.1:1337/api/cart-items/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ1MjE0NjAzLCJleHAiOjE2NDc4MDY2MDN9.BENiDZQXzMbiVUVoQ3b5NKV_SalqR0UwMc2p8ri3mxE
###
GET http://127.0.0.1:1337/api/users/me
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ1MjE0NjAzLCJleHAiOjE2NDc4MDY2MDN9.BENiDZQXzMbiVUVoQ3b5NKV_SalqR0UwMc2p8ri3mxE
###
POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
  "identifier":"alice",
  "password":"Alice123"
}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email":"alice@email.com",
  "password":"Alice123"
}
###
GET  http://localhost:3000/api/user
Content-Type: application/json

{
  "email":"alice@email.com",
  "password":"Alice123"
}
###
POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
  "username":"charlie2",
  "email":"charlie2@email.com",
  "password":"Charlie2123"
}
###
GET http://localhost:3000/api/products