GET http://localhost:1337/api/products/?populate=picture
###
GET http://localhost:1337/api/products/1?populate=picture
###
GET http://127.0.0.1:1337/api/cart-items
###
POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
  "identifier":"test",
  "password":"111111"
}
###
GET http://localhost:3000/api/products